name: Build README
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        architecture: x64
    - name: Install dependencies
      run: python -m pip install -r requirements.txt
    - name: Update README
    - env:
          RESPONSE: curl -X GET http://ws.audioscrobbler.com/2.0/?method=user.getrecenttracks&user=${{ secrets.LASTFM_USER }}&api_key=${{ secrets.LASTFM_KEY }}&format=json&limit=1
      run: |-
        python lastfm.py
        cat README.md
    - name: Commit and push if changed
      run: |-
        git diff
        git config --global user.email "readme-bot@barcode54.com"
        git config --global user.name "README-bot"
        git add -A
        git commit -m "yahoooo" || exit 0
        git push
