name: Build README
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        architecture: x64
    - name: Install dependencies
      run: python -m pip install -r requirements.txt
    - name: Update README
      env:
          LASTFM_KEY: ${{ secrets.LASTFM_KEY }}
          LASTFM_USER: ${{ secrets.LASTFM_USER }}
      run: |-
        python lastfm.py
        cat README.md
    - name: Commit and push if changed
      env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
      run: |-
        git diff
        git config --global user.email "readme-bot@barcode54.com"
        git config --global user.name "README-bot"
        git add -A
        git commit -m "yahoooo" || exit 0
        git remote set-url --push origin https://barcode54:$GITHUB_TOKEN@github.com/barcode54/barcode54
        git push
